version: '3.8'

services:
  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: knowledgesynthesis-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for Job Tracking
  redis:
    image: redis:7-alpine
    container_name: knowledgesynthesis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Neo4j Graph Database (if not already running)
  # Uncomment if you need Neo4j in Docker
  # neo4j:
  #   image: neo4j:5.12
  #   container_name: knowledgesynthesis-neo4j
  #   ports:
  #     - "7474:7474"  # HTTP
  #     - "7687:7687"  # Bolt
  #   environment:
  #     NEO4J_AUTH: neo4j/password
  #     NEO4J_PLUGINS: '["apoc"]'
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs

volumes:
  rabbitmq_data:
  redis_data:
  # neo4j_data:
  # neo4j_logs:


