# Railway Configuration for Node.js Frontend
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node -e 'require(\"http\").createServer((r,s)=>s.end(\"ok\")).listen(process.env.PORT || 3000); setInterval(()=>{},10000)'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

